drop table if exists item CASCADE;
create table item
(
    id bigint generated by default as identity,
    item_name varchar(10),
    price     integer,
    quantity  integer,
    primary key (id)
);

insert into item (item_name, price, quantity) values
 ('아이템1', 20000, 20),
 ('아이템2', 15000, 30),
 ('아이템3', 10000, 100),
 ('아이템4', 12000, 15);
